Issues and achievements in our setup:


*   Clause type leaked in instruction prompt, should have been only in response prompt. Model would have learnt a pattern, where it sees the clause type in instruction and the same in response. It would have learnt to copy the clause type IF it is found in instruction, ignores to generate it otherwise. So, our model DID NOT learn clause type classificaion. I dont wanna retrain for 6 more hours without the clause_type in the instruction prompt.
*   There is a problem with the loss function we used. Our cross entropy loss compares the predicted and the GT tokens. This wont work because, our task is a mix of classification and summarization. If our model predicts Low risk but GT is high risk, and the summary is reasonably similar, loss would be less but still we get the wrong classification. We would need 2 different loss functions or may be more importance to the critical tokens.
* Our model however, is good at legal text summarization and providing a justification for why it chose a particular risk level.
*No hallucination like the original 3b model, co-herent and meaningful sentences seen.

In [1]:
!pip cache purge
!pip install -Uq accelerate trl peft datasets
!pip uninstall -y transformers
!pip install -q git+https://github.com/huggingface/transformers.git
!pip install -Uq bitsandbytes
!pip install -q groq
!pip install -q huggingface_hub

WARNING: No matching packages
Files removed: 0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 528.8/528.8 kB 21.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 520.7/520.7 kB 38.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 17.8 MB/s eta 0:00:00
Found existing installation: transformers 5.0.0
Uninstalling transformers-5.0.0:
  Successfully uninstalled transformers-5.0.0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for transformers (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.3/138.3 kB 13.3 MB/s eta 0:00:00

In [ ]:
import os
from groq import Groq

api_key = "my_api_key"
os.environ["GROQ_API_KEY"] = api_key

client = Groq(api_key = api_key)

try:
    test_response = client.chat.completions.create(model = "llama-3.3-70b-versatile",messages=[{"role": "user", "content": "Respond with: Lets get rollin! API working!"}],
                                                 max_tokens = 20, temperature = 0.1)

    print(f"Response: {test_response.choices[0].message.content}")
    print("\n Groq API is ready!")
    print(f" Model: Llama 3.3 70B")

except Exception as e:
    print(f"Error: {e}")
    print("Check your API key and try again.")

Response: Lets get rollin! API working!

 Groq API is ready!
 Model: Llama 3.3 70B

In [ ]:
from google.colab import files
import pandas as pd

uploaded = files.upload()
df = pd.read_csv('cuad_enriched.csv')

print(f"columns: {df.columns.to_list()}")
print(f"contracts: {df['contract_name'].nunique()}")
print(f"clause types {df['clause_type'].nunique()}")

Saving cuad_enriched.csv to cuad_enriched.csv
columns: ['contract_name', 'clause_type', 'clause_text', 'enriched_context', 'metadata']
contracts: 510
clause types 41

In [ ]:
df['enriched_context'].iloc[11]

'**Contract Context:**\n    Contract Type: DISTRIBUTOR  AGREEMENT\nJurisdiction : Illinois\nRenewal Term: 10 1 years\nNotice Period to terminate renewal: None\nKey Provisions: Change of Control,Cap on Liability,Minimum Commitment\n\n    **Target Clause Type:** Governing Law\n    **Clause Text:**\n    this agreement is to be construed according to the laws of the state of illinois.'

In [ ]:

#Prompt for the 70B model.

def create_label_generation_prompt(enriched_context):
    """
    Creates a structured prompt for the 70B model

    Why this structure:
    - System prompt: Sets the role and output format ONCE
    - User prompt: The actual clause to analyze
    - JSON format: Easy to parse programmatically
    """

    system_prompt = """You are an expert legal contract analyst with 20 years of experience reviewing commercial contracts.

Your task is to analyze contract clauses and provide:
1. Risk assessment (HIGH, MEDIUM, or LOW)
2. Brief explanation of the risk
3. Plain English summary

CRITICAL RULES:
- Respond ONLY in valid JSON format
- No text before or after the JSON
- Risk level MUST be exactly: HIGH, MEDIUM, or LOW
- Consider the full contract context provided
- Base risk on jurisdiction, Renewal conditions, contract type and especially on the clause content

Response format:
{
    "risk_level": "HIGH/MEDIUM/LOW",
    "risk_reason": "2-3 sentences explaining the risk considering contract context",
    "plain_summary": "1-2 sentences in simple everyday language"
}"""

    user_prompt = f"""Analyze this contract clause:

{enriched_context}

Remember: Respond ONLY with valid JSON, nothing else."""

    return system_prompt, user_prompt

# Test it on one example
sample = df['enriched_context'].iloc[10]

system_prompt, user_prompt = create_label_generation_prompt(sample)

print("=== SYSTEM PROMPT ===")
print(system_prompt)
print("\n=== USER PROMPT ===")
print(user_prompt)

=== SYSTEM PROMPT ===
You are an expert legal contract analyst with 20 years of experience reviewing commercial contracts.

Your task is to analyze contract clauses and provide:
1. Risk assessment (HIGH, MEDIUM, or LOW)
2. Brief explanation of the risk
3. Plain English summary

CRITICAL RULES:
- Respond ONLY in valid JSON format
- No text before or after the JSON
- Risk level MUST be exactly: HIGH, MEDIUM, or LOW
- Consider the full contract context provided
- Base risk on jurisdiction, Renewal conditions, contract type and especially on the clause content

Response format:
{
    "risk_level": "HIGH/MEDIUM/LOW",
    "risk_reason": "2-3 sentences explaining the risk considering contract context",
    "plain_summary": "1-2 sentences in simple everyday language"
}

=== USER PROMPT ===
Analyze this contract clause:

**Contract Context:**
    Contract Type: DISTRIBUTOR  AGREEMENT
Jurisdiction : Illinois
Renewal Term: 10 1 years
Notice Period to terminate renewal: None
Key Provisions: Change of Control,Cap on Liability,Minimum Commitment

    **Target Clause Type:** Renewal Term
    **Clause Text:**
    if distributor complies with all of the terms of this agreement, the agreement shall be renewable on an annual basis for one (1) year terms for up to another ten (10) years on the same terms and conditions as set forth herein.

Remember: Respond ONLY with valid JSON, nothing else.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

import os
DRIVE_PATH = '/content/drive/MyDrive/CUAD_Project'
os.makedirs(DRIVE_PATH, exist_ok=True)

Mounted at /content/drive

In [ ]:
#removing clause_types that are present as metadata:

SKIP_CLAUSE_TYPES = [
    'Document Name',
    'Parties',
    'Agreement Date',
    'Effective Date',
    'Expiration Date',
]

df_to_label = df[~(df['clause_type'].isin(SKIP_CLAUSE_TYPES))].reset_index(drop=True)

sampled_df = df_to_label.groupby('clause_type').apply(lambda x: x.sample(min(110, len(x)), random_state=42)).reset_index(drop=True)
sampled_df.to_csv('sampled_df.csv', index=False)
sampled_df.shape

/tmp/ipython-input-3969280879.py:13: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_df = df_to_label.groupby('clause_type').apply(lambda x: x.sample(min(110, len(x)), random_state=42)).reset_index(drop=True)

(3455, 5)

In [ ]:
#creating a new sample from the remaining
remaining = pd.concat([df, sampled_df]).drop_duplicates(subset = ['enriched_context'], keep= False)
sampled_new = remaining.groupby('clause_type').apply(lambda x: x.sample(min(110, len(x)), random_state = 42)).reset_index(drop=True)
sampled_new.shape

/tmp/ipython-input-965187492.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  sampled_new = remaining.groupby('clause_type').apply(lambda x: x.sample(min(110, len(x)), random_state = 42)).reset_index(drop=True)

(2749, 5)

In [ ]:
#NOTE: REFER DEFINITON OF "re_run_required" FIELD IN THE BELOW CELLS.

In [ ]:
import json
from tqdm import tqdm
import time
import pandas as pd

CHECKPOINT_FILE = f'{DRIVE_PATH}/labeled_clauses.csv'
CHECKPOINT_EVERY = 50

def generate_label(enriched_context, client, max_retries=3):

  system_prompt, user_prompt = create_label_generation_prompt(enriched_context)

  for attempt in range(max_retries):
    try:
      response = client.chat.completions.create(model = "llama-3.3-70b-versatile", messages = [{'role': 'system', 'content': system_prompt}, {'role': 'user', 'content': user_prompt}],
                                     max_tokens = 300, temperature =0.1)
      response_text = response.choices[0].message.content.strip()

      parsed = json.loads(response_text)

      assert "risk_level" in parsed
      assert "risk_reason" in parsed
      assert "plain_summary" in parsed
      assert parsed["risk_level"] in ["HIGH", "MEDIUM", "LOW"]

      return parsed

    except json.JSONDecodeError:
      print(f"JSONDecodeError on attempt {attempt + 1}. Retrying...")
      time.sleep(3)

    except AssertionError:
      print(f"AssertionError[Invalid format returned] on attempt {attempt + 1}. Retrying...")
      time.sleep(3)

    except Exception as e:
      print(f"Error on attempt {attempt + 1}: {e}. Retrying...")
      time.sleep(3)

  return {
        "risk_level": "MEDIUM",
        "risk_reason": "Could not generate label after retries",
        "plain_summary": "Could not generate summary after retries"
    }


def run_label_generation(sampled_df, client):
    """
    Main generation loop with checkpointing
    """
    # Check for existing checkpoint
    if os.path.exists(CHECKPOINT_FILE):
        print(f"Checkpoint found: {CHECKPOINT_FILE}")
        labeled_df = pd.read_csv(CHECKPOINT_FILE)
        start_idx = len(labeled_df)
        print(f" Checkpoint found! Resuming from clause {start_idx}")
    else:
        labeled_df = pd.DataFrame()
        start_idx = 0
        print(f" Starting fresh generation")

    print(f"Total clauses: {len(sampled_df)}")#changing this to re-run the failed samples.
    print(f"Remaining: {2749+3455 - start_idx}")#len(sampled_df)
    print(f"Rate limit: ~30 requests/min, 1000/day\n")


    results = []

    for idx in tqdm(range(start_idx, 3455+2760)):#changing end index to 787 from 3455
      row = sampled_df.iloc[idx-3455]

      # Generate label
      label = generate_label(row['enriched_context'], client)

      # Combine with original data
      results.append({
          'contract_name': row['contract_name'],
          'clause_type': row['clause_type'],
          'clause_text': row['clause_text'],
          'enriched_context': row['enriched_context'],
          'risk_level': label['risk_level'],
          'risk_reason': label['risk_reason'],
          'plain_summary': label['plain_summary']
      })

      if (idx + 1) % CHECKPOINT_EVERY == 0:
          checkpoint_df = pd.concat(
              [labeled_df, pd.DataFrame(results)],
              ignore_index=True
          )

          checkpoint_df.to_csv(CHECKPOINT_FILE, index=False)
          print(f"\n Checkpoint saved: {idx + 1} clauses labeled")

      time.sleep(2)
      final_df = pd.concat(
        [labeled_df, pd.DataFrame(results)],
        ignore_index=True
      )
      final_df.to_csv(CHECKPOINT_FILE, index=False)

      print(f"\n Generation complete!")
      print(f" Total labeled: {len(final_df)} clauses")

    return final_df


labelled_df_new = run_label_generation(sampled_new, client)

Checkpoint found: /content/drive/MyDrive/CUAD_Project/labeled_clauses.csv
 Checkpoint found! Resuming from clause 4600
Total clauses: 2749
Remaining: 1604
Rate limit: ~30 requests/min, 1000/day

  0%|          | 1/1615 [00:03<1:22:33,  3.07s/it]

 Generation complete!
 Total labeled: 4601 clauses

  0%|          | 2/1615 [00:06<1:24:55,  3.16s/it]

 Generation complete!
 Total labeled: 4602 clauses

  0%|          | 3/1615 [00:09<1:26:18,  3.21s/it]

 Generation complete!
 Total labeled: 4603 clauses

  0%|          | 4/1615 [00:12<1:22:10,  3.06s/it]

 Generation complete!
 Total labeled: 4604 clauses

  0%|          | 5/1615 [00:15<1:21:15,  3.03s/it]

 Generation complete!
 Total labeled: 4605 clauses

  0%|          | 6/1615 [00:18<1:19:35,  2.97s/it]

 Generation complete!
 Total labeled: 4606 clauses

  0%|          | 7/1615 [00:21<1:21:41,  3.05s/it]

 Generation complete!
 Total labeled: 4607 clauses

  0%|          | 8/1615 [00:24<1:19:51,  2.98s/it]

 Generation complete!
 Total labeled: 4608 clauses

  1%|          | 9/1615 [00:27<1:20:11,  3.00s/it]

 Generation complete!
 Total labeled: 4609 clauses

  1%|          | 10/1615 [00:30<1:19:48,  2.98s/it]

 Generation complete!
 Total labeled: 4610 clauses

  1%|          | 11/1615 [00:33<1:21:22,  3.04s/it]

 Generation complete!
 Total labeled: 4611 clauses

  1%|          | 12/1615 [00:36<1:20:17,  3.01s/it]

 Generation complete!
 Total labeled: 4612 clauses

  1%|          | 13/1615 [00:39<1:20:10,  3.00s/it]

 Generation complete!
 Total labeled: 4613 clauses

  1%|          | 14/1615 [00:42<1:20:08,  3.00s/it]

 Generation complete!
 Total labeled: 4614 clauses

  1%|          | 15/1615 [00:45<1:21:44,  3.07s/it]

 Generation complete!
 Total labeled: 4615 clauses

  1%|          | 16/1615 [00:48<1:22:03,  3.08s/it]

 Generation complete!
 Total labeled: 4616 clauses

  1%|          | 17/1615 [00:51<1:21:08,  3.05s/it]

 Generation complete!
 Total labeled: 4617 clauses

  1%|          | 18/1615 [00:54<1:21:22,  3.06s/it]

 Generation complete!
 Total labeled: 4618 clauses

  1%|          | 19/1615 [00:57<1:21:41,  3.07s/it]

 Generation complete!
 Total labeled: 4619 clauses

  1%|          | 20/1615 [01:01<1:30:24,  3.40s/it]

 Generation complete!
 Total labeled: 4620 clauses

  1%|▏         | 21/1615 [01:04<1:26:41,  3.26s/it]

 Generation complete!
 Total labeled: 4621 clauses

  1%|▏         | 22/1615 [01:07<1:23:49,  3.16s/it]

 Generation complete!
 Total labeled: 4622 clauses

  1%|▏         | 23/1615 [01:11<1:23:45,  3.16s/it]

 Generation complete!
 Total labeled: 4623 clauses

  1%|▏         | 24/1615 [01:14<1:23:16,  3.14s/it]

 Generation complete!
 Total labeled: 4624 clauses

  2%|▏         | 25/1615 [01:17<1:22:21,  3.11s/it]

 Generation complete!
 Total labeled: 4625 clauses

  2%|▏         | 26/1615 [01:20<1:22:13,  3.10s/it]

 Generation complete!
 Total labeled: 4626 clauses

  2%|▏         | 27/1615 [01:23<1:23:03,  3.14s/it]

 Generation complete!
 Total labeled: 4627 clauses

  2%|▏         | 28/1615 [01:26<1:21:49,  3.09s/it]

 Generation complete!
 Total labeled: 4628 clauses

  2%|▏         | 29/1615 [01:29<1:22:25,  3.12s/it]

 Generation complete!
 Total labeled: 4629 clauses

  2%|▏         | 30/1615 [01:32<1:22:40,  3.13s/it]

 Generation complete!
 Total labeled: 4630 clauses

  2%|▏         | 31/1615 [01:36<1:23:38,  3.17s/it]

 Generation complete!
 Total labeled: 4631 clauses

  2%|▏         | 32/1615 [01:38<1:21:40,  3.10s/it]

 Generation complete!
 Total labeled: 4632 clauses

  2%|▏         | 33/1615 [01:42<1:22:38,  3.13s/it]

 Generation complete!
 Total labeled: 4633 clauses

  2%|▏         | 34/1615 [01:45<1:22:08,  3.12s/it]

 Generation complete!
 Total labeled: 4634 clauses

  2%|▏         | 35/1615 [01:48<1:23:27,  3.17s/it]

 Generation complete!
 Total labeled: 4635 clauses

  2%|▏         | 36/1615 [01:51<1:23:46,  3.18s/it]

 Generation complete!
 Total labeled: 4636 clauses

  2%|▏         | 37/1615 [01:55<1:24:12,  3.20s/it]

 Generation complete!
 Total labeled: 4637 clauses

  2%|▏         | 38/1615 [01:58<1:22:48,  3.15s/it]

 Generation complete!
 Total labeled: 4638 clauses

  2%|▏         | 39/1615 [02:01<1:23:36,  3.18s/it]

 Generation complete!
 Total labeled: 4639 clauses

  2%|▏         | 40/1615 [02:07<1:43:46,  3.95s/it]

 Generation complete!
 Total labeled: 4640 clauses

  3%|▎         | 41/1615 [02:10<1:36:20,  3.67s/it]

 Generation complete!
 Total labeled: 4641 clauses

  3%|▎         | 42/1615 [02:13<1:32:16,  3.52s/it]

 Generation complete!
 Total labeled: 4642 clauses

  3%|▎         | 43/1615 [02:16<1:30:04,  3.44s/it]

 Generation complete!
 Total labeled: 4643 clauses

  3%|▎         | 44/1615 [02:19<1:26:26,  3.30s/it]

 Generation complete!
 Total labeled: 4644 clauses

  3%|▎         | 45/1615 [02:22<1:24:58,  3.25s/it]

 Generation complete!
 Total labeled: 4645 clauses

  3%|▎         | 46/1615 [02:25<1:23:49,  3.21s/it]

 Generation complete!
 Total labeled: 4646 clauses

  3%|▎         | 47/1615 [02:28<1:24:00,  3.21s/it]

 Generation complete!
 Total labeled: 4647 clauses

  3%|▎         | 48/1615 [02:31<1:22:30,  3.16s/it]

 Generation complete!
 Total labeled: 4648 clauses

  3%|▎         | 49/1615 [02:35<1:21:51,  3.14s/it]

 Generation complete!
 Total labeled: 4649 clauses

 Checkpoint saved: 4650 clauses labeled

  3%|▎         | 50/1615 [02:38<1:23:36,  3.21s/it]

 Generation complete!
 Total labeled: 4650 clauses

  3%|▎         | 51/1615 [02:41<1:23:12,  3.19s/it]

 Generation complete!
 Total labeled: 4651 clauses

  3%|▎         | 52/1615 [02:44<1:23:03,  3.19s/it]

 Generation complete!
 Total labeled: 4652 clauses

  3%|▎         | 53/1615 [02:47<1:22:35,  3.17s/it]

 Generation complete!
 Total labeled: 4653 clauses

  3%|▎         | 54/1615 [02:51<1:22:37,  3.18s/it]

 Generation complete!
 Total labeled: 4654 clauses

  3%|▎         | 55/1615 [02:54<1:23:45,  3.22s/it]

 Generation complete!
 Total labeled: 4655 clauses

  3%|▎         | 56/1615 [02:57<1:22:43,  3.18s/it]

 Generation complete!
 Total labeled: 4656 clauses

  4%|▎         | 57/1615 [03:00<1:21:58,  3.16s/it]

 Generation complete!
 Total labeled: 4657 clauses

  4%|▎         | 58/1615 [03:03<1:20:16,  3.09s/it]

 Generation complete!
 Total labeled: 4658 clauses

  4%|▎         | 59/1615 [03:06<1:22:28,  3.18s/it]

 Generation complete!
 Total labeled: 4659 clauses

  4%|▎         | 60/1615 [03:10<1:22:14,  3.17s/it]

 Generation complete!
 Total labeled: 4660 clauses

  4%|▍         | 61/1615 [03:13<1:21:23,  3.14s/it]

 Generation complete!
 Total labeled: 4661 clauses

  4%|▍         | 62/1615 [03:16<1:20:53,  3.13s/it]

 Generation complete!
 Total labeled: 4662 clauses

  4%|▍         | 63/1615 [03:19<1:22:07,  3.17s/it]

 Generation complete!
 Total labeled: 4663 clauses

  4%|▍         | 64/1615 [03:22<1:20:00,  3.10s/it]

 Generation complete!
 Total labeled: 4664 clauses
JSONDecodeError on attempt 1. Retrying...
JSONDecodeError on attempt 2. Retrying...

  4%|▍         | 65/1615 [03:33<2:19:21,  5.39s/it]

 Generation complete!
 Total labeled: 4665 clauses

  4%|▍         | 66/1615 [03:36<2:01:55,  4.72s/it]

 Generation complete!
 Total labeled: 4666 clauses

  4%|▍         | 67/1615 [03:39<1:48:53,  4.22s/it]

 Generation complete!
 Total labeled: 4667 clauses

  4%|▍         | 68/1615 [03:42<1:39:22,  3.85s/it]

 Generation complete!
 Total labeled: 4668 clauses

  4%|▍         | 69/1615 [03:45<1:32:40,  3.60s/it]

 Generation complete!
 Total labeled: 4669 clauses

  4%|▍         | 70/1615 [03:48<1:28:40,  3.44s/it]

 Generation complete!
 Total labeled: 4670 clauses

  4%|▍         | 71/1615 [03:51<1:26:41,  3.37s/it]

 Generation complete!
 Total labeled: 4671 clauses

  4%|▍         | 72/1615 [03:54<1:23:53,  3.26s/it]

 Generation complete!
 Total labeled: 4672 clauses

  5%|▍         | 73/1615 [03:58<1:24:46,  3.30s/it]

 Generation complete!
 Total labeled: 4673 clauses

  5%|▍         | 74/1615 [04:01<1:22:35,  3.22s/it]

 Generation complete!
 Total labeled: 4674 clauses

  5%|▍         | 75/1615 [04:04<1:22:10,  3.20s/it]

 Generation complete!
 Total labeled: 4675 clauses

  5%|▍         | 76/1615 [04:07<1:20:48,  3.15s/it]

 Generation complete!
 Total labeled: 4676 clauses

  5%|▍         | 77/1615 [04:10<1:20:28,  3.14s/it]

 Generation complete!
 Total labeled: 4677 clauses

  5%|▍         | 78/1615 [04:13<1:19:50,  3.12s/it]

 Generation complete!
 Total labeled: 4678 clauses

  5%|▍         | 79/1615 [04:16<1:19:16,  3.10s/it]

 Generation complete!
 Total labeled: 4679 clauses

  5%|▍         | 80/1615 [04:19<1:19:25,  3.10s/it]

 Generation complete!
 Total labeled: 4680 clauses

  5%|▌         | 81/1615 [04:22<1:21:15,  3.18s/it]

 Generation complete!
 Total labeled: 4681 clauses

  5%|▌         | 82/1615 [04:25<1:19:47,  3.12s/it]

 Generation complete!
 Total labeled: 4682 clauses

  5%|▌         | 83/1615 [04:28<1:18:45,  3.08s/it]

 Generation complete!
 Total labeled: 4683 clauses

  5%|▌         | 84/1615 [04:31<1:17:55,  3.05s/it]

 Generation complete!
 Total labeled: 4684 clauses

  5%|▌         | 85/1615 [04:35<1:19:53,  3.13s/it]

 Generation complete!
 Total labeled: 4685 clauses

  5%|▌         | 86/1615 [04:38<1:19:31,  3.12s/it]

 Generation complete!
 Total labeled: 4686 clauses

  5%|▌         | 87/1615 [04:41<1:18:58,  3.10s/it]

 Generation complete!
 Total labeled: 4687 clauses

  5%|▌         | 88/1615 [04:44<1:18:52,  3.10s/it]

 Generation complete!
 Total labeled: 4688 clauses

  6%|▌         | 89/1615 [04:47<1:20:09,  3.15s/it]

 Generation complete!
 Total labeled: 4689 clauses

  6%|▌         | 90/1615 [04:50<1:20:17,  3.16s/it]

 Generation complete!
 Total labeled: 4690 clauses

  6%|▌         | 91/1615 [04:54<1:19:55,  3.15s/it]

 Generation complete!
 Total labeled: 4691 clauses

  6%|▌         | 92/1615 [04:57<1:19:39,  3.14s/it]

 Generation complete!
 Total labeled: 4692 clauses

  6%|▌         | 93/1615 [05:00<1:20:57,  3.19s/it]

 Generation complete!
 Total labeled: 4693 clauses

  6%|▌         | 94/1615 [05:03<1:20:59,  3.20s/it]

 Generation complete!
 Total labeled: 4694 clauses

  6%|▌         | 95/1615 [05:06<1:20:47,  3.19s/it]

 Generation complete!
 Total labeled: 4695 clauses

  6%|▌         | 96/1615 [05:09<1:19:10,  3.13s/it]

 Generation complete!
 Total labeled: 4696 clauses

  6%|▌         | 97/1615 [05:13<1:19:58,  3.16s/it]

 Generation complete!
 Total labeled: 4697 clauses

  6%|▌         | 98/1615 [05:16<1:20:10,  3.17s/it]

 Generation complete!
 Total labeled: 4698 clauses

  6%|▌         | 99/1615 [05:19<1:19:45,  3.16s/it]

 Generation complete!
 Total labeled: 4699 clauses

 Checkpoint saved: 4700 clauses labeled

  6%|▌         | 100/1615 [05:23<1:23:39,  3.31s/it]

 Generation complete!
 Total labeled: 4700 clauses

  6%|▋         | 101/1615 [05:26<1:23:08,  3.30s/it]

 Generation complete!
 Total labeled: 4701 clauses

  6%|▋         | 102/1615 [05:29<1:24:11,  3.34s/it]

 Generation complete!
 Total labeled: 4702 clauses

  6%|▋         | 103/1615 [05:32<1:22:05,  3.26s/it]

 Generation complete!
 Total labeled: 4703 clauses

  6%|▋         | 104/1615 [05:35<1:20:22,  3.19s/it]

 Generation complete!
 Total labeled: 4704 clauses

  7%|▋         | 105/1615 [05:39<1:20:29,  3.20s/it]

 Generation complete!
 Total labeled: 4705 clauses

  7%|▋         | 106/1615 [05:42<1:19:55,  3.18s/it]

 Generation complete!
 Total labeled: 4706 clauses

  7%|▋         | 107/1615 [05:45<1:19:16,  3.15s/it]

 Generation complete!
 Total labeled: 4707 clauses

  7%|▋         | 108/1615 [05:48<1:17:36,  3.09s/it]

 Generation complete!
 Total labeled: 4708 clauses

  7%|▋         | 109/1615 [05:51<1:18:23,  3.12s/it]

 Generation complete!
 Total labeled: 4709 clauses

  7%|▋         | 110/1615 [05:54<1:18:01,  3.11s/it]

 Generation complete!
 Total labeled: 4710 clauses

  7%|▋         | 111/1615 [05:57<1:18:00,  3.11s/it]

 Generation complete!
 Total labeled: 4711 clauses

  7%|▋         | 112/1615 [06:00<1:17:39,  3.10s/it]

 Generation complete!
 Total labeled: 4712 clauses

  7%|▋         | 113/1615 [06:04<1:18:44,  3.15s/it]

 Generation complete!
 Total labeled: 4713 clauses

  7%|▋         | 114/1615 [06:07<1:18:42,  3.15s/it]

 Generation complete!
 Total labeled: 4714 clauses

  7%|▋         | 115/1615 [06:10<1:17:57,  3.12s/it]

 Generation complete!
 Total labeled: 4715 clauses

  7%|▋         | 116/1615 [06:13<1:17:35,  3.11s/it]

 Generation complete!
 Total labeled: 4716 clauses

  7%|▋         | 117/1615 [06:16<1:17:02,  3.09s/it]

 Generation complete!
 Total labeled: 4717 clauses

  7%|▋         | 118/1615 [06:19<1:16:35,  3.07s/it]

 Generation complete!
 Total labeled: 4718 clauses

  7%|▋         | 119/1615 [06:22<1:16:07,  3.05s/it]

 Generation complete!
 Total labeled: 4719 clauses

  7%|▋         | 120/1615 [06:25<1:14:34,  2.99s/it]

 Generation complete!
 Total labeled: 4720 clauses

  7%|▋         | 121/1615 [06:28<1:15:50,  3.05s/it]

 Generation complete!
 Total labeled: 4721 clauses

  8%|▊         | 122/1615 [06:31<1:16:19,  3.07s/it]

 Generation complete!
 Total labeled: 4722 clauses

  8%|▊         | 123/1615 [06:34<1:16:08,  3.06s/it]

 Generation complete!
 Total labeled: 4723 clauses

  8%|▊         | 124/1615 [06:37<1:15:38,  3.04s/it]

 Generation complete!
 Total labeled: 4724 clauses

  8%|▊         | 125/1615 [06:40<1:16:18,  3.07s/it]

 Generation complete!
 Total labeled: 4725 clauses

  8%|▊         | 126/1615 [06:43<1:15:36,  3.05s/it]

 Generation complete!
 Total labeled: 4726 clauses

  8%|▊         | 127/1615 [06:46<1:15:26,  3.04s/it]

 Generation complete!
 Total labeled: 4727 clauses

  8%|▊         | 128/1615 [06:49<1:15:30,  3.05s/it]

 Generation complete!
 Total labeled: 4728 clauses

  8%|▊         | 129/1615 [06:52<1:16:11,  3.08s/it]

 Generation complete!
 Total labeled: 4729 clauses

  8%|▊         | 130/1615 [06:56<1:16:51,  3.11s/it]

 Generation complete!
 Total labeled: 4730 clauses

  8%|▊         | 131/1615 [06:59<1:15:28,  3.05s/it]

 Generation complete!
 Total labeled: 4731 clauses

  8%|▊         | 132/1615 [07:02<1:15:42,  3.06s/it]

 Generation complete!
 Total labeled: 4732 clauses

  8%|▊         | 133/1615 [07:05<1:16:08,  3.08s/it]

 Generation complete!
 Total labeled: 4733 clauses

  8%|▊         | 134/1615 [07:08<1:17:16,  3.13s/it]

 Generation complete!
 Total labeled: 4734 clauses

  8%|▊         | 135/1615 [07:11<1:16:47,  3.11s/it]

 Generation complete!
 Total labeled: 4735 clauses

  8%|▊         | 136/1615 [07:14<1:15:37,  3.07s/it]

 Generation complete!
 Total labeled: 4736 clauses

  8%|▊         | 137/1615 [07:17<1:15:23,  3.06s/it]

 Generation complete!
 Total labeled: 4737 clauses

  9%|▊         | 138/1615 [07:20<1:16:07,  3.09s/it]

 Generation complete!
 Total labeled: 4738 clauses

  9%|▊         | 139/1615 [07:23<1:15:50,  3.08s/it]

 Generation complete!
 Total labeled: 4739 clauses

  9%|▊         | 140/1615 [07:26<1:16:24,  3.11s/it]

 Generation complete!
 Total labeled: 4740 clauses

  9%|▊         | 141/1615 [07:29<1:15:42,  3.08s/it]

 Generation complete!
 Total labeled: 4741 clauses

  9%|▉         | 142/1615 [07:33<1:16:46,  3.13s/it]

 Generation complete!
 Total labeled: 4742 clauses

  9%|▉         | 143/1615 [07:36<1:16:14,  3.11s/it]

 Generation complete!
 Total labeled: 4743 clauses

  9%|▉         | 144/1615 [07:39<1:15:27,  3.08s/it]

 Generation complete!
 Total labeled: 4744 clauses

  9%|▉         | 145/1615 [07:42<1:14:39,  3.05s/it]

 Generation complete!
 Total labeled: 4745 clauses

  9%|▉         | 146/1615 [07:45<1:17:24,  3.16s/it]

 Generation complete!
 Total labeled: 4746 clauses

  9%|▉         | 147/1615 [07:48<1:17:06,  3.15s/it]

 Generation complete!
 Total labeled: 4747 clauses

  9%|▉         | 148/1615 [07:51<1:16:13,  3.12s/it]

 Generation complete!
 Total labeled: 4748 clauses

  9%|▉         | 149/1615 [07:54<1:15:08,  3.08s/it]

 Generation complete!
 Total labeled: 4749 clauses

 Checkpoint saved: 4750 clauses labeled

  9%|▉         | 150/1615 [07:58<1:20:29,  3.30s/it]

 Generation complete!
 Total labeled: 4750 clauses

  9%|▉         | 151/1615 [08:01<1:20:01,  3.28s/it]

 Generation complete!
 Total labeled: 4751 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99993, Requested 399. Please try again in 5m38.688s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99989, Requested 399. Please try again in 5m35.232s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99986, Requested 399. Please try again in 5m32.64s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

  9%|▉         | 152/1615 [08:13<2:19:58,  5.74s/it]

 Generation complete!
 Total labeled: 4752 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99979, Requested 372. Please try again in 5m3.264s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99976, Requested 372. Please try again in 5m0.672s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99972, Requested 372. Please try again in 4m57.216s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

  9%|▉         | 153/1615 [08:25<3:03:27,  7.53s/it]

 Generation complete!
 Total labeled: 4753 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99966, Requested 407. Please try again in 5m22.272s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99962, Requested 407. Please try again in 5m18.816s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99959, Requested 407. Please try again in 5m16.224s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|▉         | 154/1615 [08:36<3:33:48,  8.78s/it]

 Generation complete!
 Total labeled: 4754 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99952, Requested 352. Please try again in 4m22.656s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99949, Requested 352. Please try again in 4m20.064s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99945, Requested 352. Please try again in 4m16.608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|▉         | 155/1615 [08:48<3:55:29,  9.68s/it]

 Generation complete!
 Total labeled: 4755 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99939, Requested 407. Please try again in 4m58.944s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99935, Requested 407. Please try again in 4m55.488s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99932, Requested 407. Please try again in 4m52.895999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|▉         | 156/1615 [09:00<4:08:39, 10.23s/it]

 Generation complete!
 Total labeled: 4756 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99925, Requested 329. Please try again in 3m39.456s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99922, Requested 329. Please try again in 3m36.864s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99918, Requested 329. Please try again in 3m33.408s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|▉         | 157/1615 [09:11<4:18:03, 10.62s/it]

 Generation complete!
 Total labeled: 4757 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99912, Requested 353. Please try again in 3m48.96s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99909, Requested 353. Please try again in 3m46.368s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99905, Requested 353. Please try again in 3m42.911999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|▉         | 158/1615 [09:23<4:24:22, 10.89s/it]

 Generation complete!
 Total labeled: 4758 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99899, Requested 364. Please try again in 3m47.232s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99895, Requested 364. Please try again in 3m43.775999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99892, Requested 364. Please try again in 3m41.184s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|▉         | 159/1615 [09:34<4:28:48, 11.08s/it]

 Generation complete!
 Total labeled: 4759 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99885, Requested 479. Please try again in 5m14.496s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99882, Requested 479. Please try again in 5m11.904s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99878, Requested 479. Please try again in 5m8.448s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|▉         | 160/1615 [09:46<4:31:52, 11.21s/it]

 Generation complete!
 Total labeled: 4760 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99872, Requested 433. Please try again in 4m23.52s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99869, Requested 433. Please try again in 4m20.928s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99865, Requested 433. Please try again in 4m17.471999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|▉         | 161/1615 [09:57<4:34:08, 11.31s/it]

 Generation complete!
 Total labeled: 4761 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99859, Requested 394. Please try again in 3m38.592s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99855, Requested 394. Please try again in 3m35.136s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99852, Requested 394. Please try again in 3m32.543999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|█         | 162/1615 [10:09<4:35:24, 11.37s/it]

 Generation complete!
 Total labeled: 4762 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99845, Requested 411. Please try again in 3m41.184s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99842, Requested 411. Please try again in 3m38.592s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99838, Requested 411. Please try again in 3m35.136s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|█         | 163/1615 [10:20<4:36:23, 11.42s/it]

 Generation complete!
 Total labeled: 4763 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99832, Requested 347. Please try again in 2m34.656s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99828, Requested 347. Please try again in 2m31.2s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99825, Requested 347. Please try again in 2m28.608s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|█         | 164/1615 [10:32<4:37:04, 11.46s/it]

 Generation complete!
 Total labeled: 4764 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99819, Requested 321. Please try again in 2m0.96s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99815, Requested 321. Please try again in 1m57.504s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99812, Requested 321. Please try again in 1m54.912s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|█         | 165/1615 [10:43<4:38:39, 11.53s/it]

 Generation complete!
 Total labeled: 4765 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99805, Requested 376. Please try again in 2m36.384s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99802, Requested 376. Please try again in 2m33.792s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99798, Requested 376. Please try again in 2m30.336s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|█         | 166/1615 [10:55<4:39:44, 11.58s/it]

 Generation complete!
 Total labeled: 4766 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99792, Requested 372. Please try again in 2m21.696s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99788, Requested 372. Please try again in 2m18.24s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99784, Requested 372. Please try again in 2m14.783999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|█         | 167/1615 [11:07<4:40:42, 11.63s/it]

 Generation complete!
 Total labeled: 4767 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99778, Requested 437. Please try again in 3m5.76s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99774, Requested 437. Please try again in 3m2.304s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99771, Requested 437. Please try again in 2m59.712s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|█         | 168/1615 [11:19<4:40:12, 11.62s/it]

 Generation complete!
 Total labeled: 4768 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99765, Requested 344. Please try again in 1m34.176s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99761, Requested 344. Please try again in 1m30.72s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99757, Requested 344. Please try again in 1m27.264s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|█         | 169/1615 [11:30<4:39:21, 11.59s/it]

 Generation complete!
 Total labeled: 4769 clauses
Error on attempt 1: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99751, Requested 330. Please try again in 1m9.984s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 2: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99748, Requested 330. Please try again in 1m7.391999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...
Error on attempt 3: Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01khry8nsje83r1djj1f1fqqrn` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99744, Requested 330. Please try again in 1m3.936s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}. Retrying...

 10%|█         | 169/1615 [11:41<1:40:04,  4.15s/it]

KeyboardInterrupt:

In [ ]:
CHECKPOINT_FILE = f'{DRIVE_PATH}/labeled_clauses.csv'
labelled_df = pd.read_csv(CHECKPOINT_FILE)

In [ ]:
labelled_df.shape

(4751, 7)

In [ ]:
labelled_df = labelled_df[~(labelled_df['risk_reason'].str.lower().str.contains('could not generate'))]
labelled_df.to_csv(CHECKPOINT_FILE, index = False)

In [ ]:
labelled_df.shape

(4751, 7)

In [ ]:
labelled_df.shape

(4751, 7)

In [ ]:
#taking the samples that need to be re-run, cos the summary was not generated.
re_run_required = labelled_df[labelled_df['plain_summary'].str.lower().str.contains('could not generate')]
re_run_required.shape

(0, 7)

In [ ]:
labelled_df_new=labelled_df[~(labelled_df['plain_summary'].str.lower().str.contains('could not generate'))]
labelled_df_new.shape

(3439, 7)

In [ ]:
labelled_df_new.to_csv(CHECKPOINT_FILE, index=False)

In [ ]:
remaining = pd.concat([df, sampled_df]).drop_duplicates(keep=False)
remaining.shape

(10361, 5)

In [ ]:
excel = pd.read_excel(f'{DRIVE_PATH}/labeled_clauses_proper.xlsx')
excel.shape

(3452, 7)

In [ ]:
labelled_df.shape

(4751, 7)

In [ ]:
combined_df = pd.concat([labelled_df, excel], ignore_index=True).drop_duplicates(subset = ['enriched_context'], keep='first')
combined_df.shape

(5488, 8)

In [ ]:
#reading the combined_csv from drive
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

import os
DRIVE_PATH = '/content/drive/MyDrive/CUAD_Project'
combined_df = pd.read_csv(f'{DRIVE_PATH}/final_clauses.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
def format_instruction_response(row):
  instruction = f"""Analyse the following clause and provide:
1. Clause type classification
2. Risk assessment (HIGH/MEDIUM/LOW) with explanation
3. Plain English summary

{row['enriched_context']}

Provide your analysis:

"""
  response = f"""**Clause Type:** {row['clause_type']}

**Risk Assessment:** {row['risk_level']}
**Explanation:** {row['risk_reason']}

**Plain English Summary:** {row['plain_summary']}"""

  full_text = f"{instruction}\n\n{response}"

  return {'instruction': instruction, 'response': response, 'full_text': full_text}



training_data = combined_df.apply(format_instruction_response, axis=1).tolist()
training_df = pd.DataFrame(training_data)
training_df.head(2)

print(f"Created {len(training_df)} training examples")

print(f"\nTraining Example:")
print("="*80)
print("INSTRUCTION:")
print(training_df['instruction'].iloc[0][:300] + "...")
print("\nRESPONSE:")
print(training_df['response'].iloc[0][:300] + "...")
print("="*80)

Created 5488 training examples

Training Example:
================================================================================
INSTRUCTION:
Analyse the following clause and provide:
1. Clause type classification
2. Risk assessment (HIGH/MEDIUM/LOW) with explanation
3. Plain English summary

**Contract Context:**
    Contract Type: INTELLECTUAL PROPERTY AGREEMENT
Jurisdiction : Georgia
Renewal Term: Not Applicable
Notice Period to termin...

RESPONSE:
**Clause Type:** Affiliate License-Licensee

**Risk Assessment:** MEDIUM
**Explanation:** The sublicense rights granted to Equifax may pose a risk of losing control over the licensed Certegy materials, as Equifax is allowed to grant sublicenses to other parties. This could lead to potential intellec...
================================================================================

In [ ]:
print(training_df.iloc[0]['full_text'])

Analyse the following clause and provide:
1. Clause type classification
2. Risk assessment (HIGH/MEDIUM/LOW) with explanation
3. Plain English summary

**Contract Context:**
    Contract Type: INTELLECTUAL PROPERTY AGREEMENT
Jurisdiction : Georgia
Renewal Term: Not Applicable
Notice Period to terminate renewal: None
Key Provisions: Change of Control,Cap on Liability,Minimum Commitment

    **Target Clause Type:** Affiliate License-Licensee
    **Clause Text:**
    the sublicense rights granted to equifax pursuant to section 4.4(a) include the right for equifax to grant sublicenses to the licensed certegy materials (excluding the utility

Provide your analysis:



**Clause Type:** Affiliate License-Licensee

**Risk Assessment:** MEDIUM
**Explanation:** The sublicense rights granted to Equifax may pose a risk of losing control over the licensed Certegy materials, as Equifax is allowed to grant sublicenses to other parties. This could lead to potential intellectual property infringement or misuse, especially since the contract does not specify any conditions or restrictions on these sublicenses. However, the fact that the utility is excluded from sublicensing mitigates this risk to some extent.

**Plain English Summary:** Equifax is allowed to grant sublicenses to other parties, which may lead to a loss of control over the licensed materials, but with some limitations to reduce the risk.

In [ ]:
#TRAIN/VAL/TEST SPLIT

from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(training_df, test_size=0.2, random_state=42, stratify = combined_df['clause_type'])
train_df.to_csv(f'{DRIVE_PATH}/train_new.csv', index=False)
val_df.to_csv(f'{DRIVE_PATH}/val_new.csv', index=False)

print(f"Train: {len(train_df)}")
print(f"Val: {len(val_df)}")

Train: 4390
Val: 1098

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

import os
DRIVE_PATH = '/content/drive/MyDrive/CUAD_Project'

train_df = pd.read_csv(f'{DRIVE_PATH}/train_new.csv')
val_df = pd.read_csv(f'{DRIVE_PATH}/val_new.csv')

Mounted at /content/drive

In [ ]:
train_df.columns

Index(['instruction', 'response', 'full_text'], dtype='object')

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
import torch

MODEL_NAME = "meta-llama/Llama-3.2-3B-Instruct" #the model we need to finetune

#initialising the quantisation config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type = 'nf4',
    bnb_4bit_use_double_quant = True,
    bnb_4bit_compute_dtype = torch.float16
)

#initialising the base model, passing the quantisation config to it.
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, quantization_config = bnb_config, device_map = 'auto', trust_remote_code = True, )


#loading the right tokenizer, autotokenizer takes care of it.
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code = True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = 'right'


#prepare the model for k-bit training, this ensures gradient checkpointing, makes sure the base model weights are frozen
#and carries out the computation in float32 for layernorm and output layers, to ensure precision in calculation.
model = prepare_model_for_kbit_training(model)
print("successfully loaded base model in 4 bit")
print(f"Memory used: {torch.cuda.memory_allocated() / 1e9:.2f} GB")

config.json:   0%|          | 0.00/878 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/20.9k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/54.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

successfully loaded base model in 4 bit
Memory used: 3.04 GB

In [ ]:
#LoRA configuration

lora_config = LoraConfig(r=16,
                         lora_alpha=32,
                         target_modules = ['q_proj', 'k_proj', 'v_proj', 'o_proj',
                                           'up_proj', 'down_proj', 'gate_proj'],#up, down and gate proj correspond to the layers in the mlp
                         lora_dropout=0.05,
                         bias='none',
                         task_type='CAUSAL_LM')

#Apply LoRA to model
model = get_peft_model(model, lora_config)
print("successfully applied LoRA")


model.print_trainable_parameters()

successfully applied LoRA
trainable params: 24,313,856 || all params: 3,237,063,680 || trainable%: 0.7511

In [ ]:
# ========================================
# DIAGNOSTIC: Check Your Actual Lengths
# ========================================

# Check your formatted data lengths
print(" Checking sequence lengths in your data...\n")

sample_lengths = []

for i in range(min(100, len(train_df))):
    instruction = train_df.iloc[i]['instruction']
    response = train_df.iloc[i]['response']

    # Format as chat
    messages = [
        {"role": "user", "content": instruction},
        {"role": "assistant", "content": response}
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )

    # Tokenize to get length
    tokens = tokenizer(text, add_special_tokens=True)
    length = len(tokens['input_ids'])
    sample_lengths.append(length)

# Statistics
import numpy as np
print(f"Sequence Length Statistics (100 samples):")
print(f"   Min:    {min(sample_lengths)}")
print(f"   Max:    {max(sample_lengths)}")
print(f"   Mean:   {np.mean(sample_lengths):.0f}")
print(f"   Median: {np.median(sample_lengths):.0f}")
print(f"   95th percentile: {np.percentile(sample_lengths, 95):.0f}")

# How many exceed 2048?
over_limit = sum(1 for l in sample_lengths if l > 2048)
print(f"\n Sequences over 2048 tokens: {over_limit}/{len(sample_lengths)} ({over_limit/len(sample_lengths)*100:.1f}%)")

if over_limit > 0:
    print(f"   These will be TRUNCATED, losing response data!")

 Checking sequence lengths in your data...

Sequence Length Statistics (100 samples):
   Min:    261
   Max:    577
   Mean:   356
   Median: 338
   95th percentile: 481

 Sequences over 2048 tokens: 0/100 (0.0%)

In [ ]:
from datasets import Dataset

def format_for_training(examples):

  formatted_texts = []

  for instruction, response in zip(examples['instruction'], examples['response']):

    messages = [{'role': 'user', 'content': instruction}, {'role': 'assistant', 'content': response}]

    text = tokenizer.apply_chat_template(messages, tokenize = False, add_generation_prompt = False)

    formatted_texts.append(text)


  #making return_attention_mask as True cos the datacollator will use the mask as a template to pad... Dynamic padding will be taken care of by the datacollator.
  model_inputs = tokenizer(formatted_texts, padding = False, max_length = 2048, truncation = True, return_tensors = None, return_attention_mask = True)

  #no need to pad here.
  model_inputs["labels"] = [input_ids.copy() for input_ids in model_inputs["input_ids"]]

  labels =[]

  #Instruction Masking...[probably not drastic immprovement in scores, still a good learning exercise]
  for i,(instruction, response) in enumerate(zip(examples['instruction'], examples['response'])):

    response_tokens = tokenizer(response, add_special_tokens = False, max_length = 2048, truncation = True)['input_ids']

    full_text = model_inputs['input_ids'][i]

    response_start = len(full_text) - len(response_tokens)

    temp = [-100] *len(full_text) #start with all tokens masked

    temp[response_start:] = full_text[response_start:] #unmask only the response tokens

    labels.append(temp)

  model_inputs['labels'] = labels

  return model_inputs




print("Converting data to HF Dataset format...")

train_dataset = Dataset.from_pandas(train_df[['instruction', 'response']])
val_dataset = Dataset.from_pandas(val_df[['instruction', 'response']])

print("Tokenizing Datasets...")

train_dataset = train_dataset.map(format_for_training, batched = True, remove_columns = ['instruction', 'response'], desc = "Formatting Train data")
val_dataset = val_dataset.map(format_for_training, batched = True, remove_columns = ['instruction', 'response'], desc = "Formatting Val data")

print("Datasets tokenized and formatted!")

print(f"Train dataset: {len(train_dataset)} examples")
print(f"Val dataset: {len(val_dataset)} examples")


print(f"\n Sample verification:")
for i in range(3):
    labels = train_dataset[i]['labels']
    learnable = sum(1 for l in labels if l != -100)
    print(f"Sample {i}: {learnable} learnable tokens")

Converting data to HF Dataset format...
Tokenizing Datasets...

Formatting Train data:   0%|          | 0/4390 [00:00<?, ? examples/s]

NameError: name 'tokenizer' is not defined

In [ ]:
#Training Hyperparameters:

from transformers import TrainingArguments

OUTPUT_DIR = f"{DRIVE_PATH}/llama-3.2-3b-contract-analyzer"

os.environ["TENSORBOARD_LOGGING_DIR"] = f"{DRIVE_PATH}/logs2"

training_args = TrainingArguments(
    output_dir = OUTPUT_DIR,
    run_name = 'contract-clause-analysis',

    #Training Schedule
    num_train_epochs = 3,
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 16,
    per_device_eval_batch_size = 1,

    #Learning Rate params

    learning_rate = 2e-4,
    lr_scheduler_type = 'cosine',
    warmup_ratio = 0.03, #LR starts from 0 and reaches the peak of 2e-4 at the 3% of the total training steps and declines from there, big updates early on, finegrained updates towards the end.

    #Optimization
    optim = 'adamw_torch', #The paged version pushes data to RAM if VRAM is about to run out of memory, 8 bit version optimizes memory footprint.
    weight_decay = 0.01, #Adds a penalty to the model weights itself, not the LR, to make sure no weight is over-focused.
    max_grad_norm = 1.0, #Clips gradient and does not allow a norm of more than 1


    #Evaluation and Saving
    eval_strategy = 'steps', #model run on eval data every 50 train steps
    eval_steps = 100,
    save_strategy = 'steps', #model weights saved every 50 steps, usually in sync with the eval strategy so that we dont lose any info that was used for eval
    save_steps = 100,
    save_total_limit = 3, #saves the last 3 checkpoints.
    load_best_model_at_end = True,
    metric_for_best_model = 'eval_loss',

    #Logging
    logging_dir = f"{DRIVE_PATH}/logs",
    logging_steps = 10,
    report_to = 'none',

    #Memory Optimization
    gradient_checkpointing = True,
    fp16 =False,
    bf16 = False,

    remove_unused_columns = False,
    label_names = ['labels']

)

print("Training arguments configured")
print(f"\nKey Settings:")
print(f"Effective batch size: {training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps}")
print(f"Total epochs: {training_args.num_train_epochs}")
print(f"Learning rate: {training_args.learning_rate}")
print(f"Warmup steps: ~{int(len(train_dataset) / (training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps) * training_args.num_train_epochs * training_args.warmup_ratio)}")

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Training arguments configured

Key Settings:
Effective batch size: 16
Total epochs: 3
Learning rate: 0.0002
Warmup steps: ~24

In [ ]:
#Supervised Fine-Tuning

from trl import SFTTrainer
from transformers import DataCollatorForLanguageModeling
from transformers import DataCollatorForSeq2Seq


#data_collator = DataCollatorForLanguageModeling(tokenizer, mlm = False)

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
    padding=True,        # Pad dynamically
    pad_to_multiple_of=8,  # For efficiency
    label_pad_token_id=-100,  # Pad labels with -100
    return_tensors="pt"
)

#passing the datacollator handles the dynamic padding, max length sequence per batch

trainer = SFTTrainer(
    model = model,
    train_dataset = train_dataset,
    args = training_args,
    processing_class = tokenizer,
    eval_dataset = val_dataset,
    data_collator = data_collator
)

print("Trainer initialized!")
print("\nTraining will begin with:")
print(f"Total training steps: {trainer.state.max_steps if hasattr(trainer.state, 'max_steps') else 'calculating...'}")
print(f"Evaluation every: {training_args.eval_steps} steps")
print(f"Checkpoint every: {training_args.save_steps} steps")

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Truncating train dataset:   0%|          | 0/4390 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/1098 [00:00<?, ? examples/s]

Trainer initialized!

Training will begin with:
Total training steps: 0
Evaluation every: 100 steps
Checkpoint every: 100 steps

In [ ]:


import time

print("STARTING FINE-TUNING!")
print("Estimated time: 4-6 hours")
print("Checkpoints: Every 100 steps to Google Drive\n")

start_time = time.time()

# Train (has built-in progress bar)
trainer.train()

# Done
elapsed = (time.time() - start_time) / 3600
print(f"\nTRAINING COMPLETE in {elapsed:.2f} hours")

# Save
print("Saving model...")
final_model_path = f"{DRIVE_PATH}/final_model"
trainer.save_model(final_model_path)
tokenizer.save_pretrained(final_model_path)

print(f"Saved to: {final_model_path}")

STARTING FINE-TUNING!
Estimated time: 4-6 hours
Checkpoints: Every 100 steps to Google Drive

**Reloading Checkpoint beccause we lost GPU access **

In [ ]:
#Re-Install the libraries and load the data files before running this cell...
import os

checkpoint_dir = f"{DRIVE_PATH}/llama-3.2-3b-contract-analyzer"
latest_checkpoint = f"{checkpoint_dir}/checkpoint-700"

print(f"Checkpoint loaded : {latest_checkpoint}")

Checkpoint loaded : /content/drive/MyDrive/CUAD_Project/llama-3.2-3b-contract-analyzer/checkpoint-700

In [ ]:
#Pasting the model loading cell here, making some changes to load from checkpoint:

#NOTE: Had to login to HF space with a token from account, as we are running from a different co

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, PeftModel
import torch

MODEL_NAME = "meta-llama/Llama-3.2-3B-Instruct" #the model we need to finetune

#initialising the quantisation config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type = 'nf4',
    bnb_4bit_use_double_quant = True,
    bnb_4bit_compute_dtype = torch.float16
)

#initialising the base model, passing the quantisation config to it.
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, quantization_config = bnb_config, device_map = 'auto', trust_remote_code = True)

#Prepare base model for kbit training
base_model = prepare_model_for_kbit_training(model)

#apply the cehckpointed lora adapters to the base model
model = PeftModel.from_pretrained(base_model, latest_checkpoint, is_trainable = True, torch_dtype=torch.float16)


#loading the right tokenizer, autotokenizer takes care of it.
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, trust_remote_code = True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = 'right'




#loading model from latest checkpoint
print(f"successfully loaded base model from checkpoint - {latest_checkpoint}")
print(f"Memory used: {torch.cuda.memory_allocated() / 1e9:.2f} GB")

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/54.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/296 [00:00<?, ?B/s]

successfully loaded base model from checkpoint - /content/drive/MyDrive/CUAD_Project/llama-3.2-3b-contract-analyzer/checkpoint-700
Memory used: 3.13 GB

In [ ]:
#Tokenize the data as done before


from datasets import Dataset

def format_for_training(examples):

  formatted_texts = []

  for instruction, response in zip(examples['instruction'], examples['response']):

    messages = [{'role': 'user', 'content': instruction}, {'role': 'assistant', 'content': response}]

    text = tokenizer.apply_chat_template(messages, tokenize = False, add_generation_prompt = False)

    formatted_texts.append(text)


  #making return_attention_mask as True cos the datacollator will use the mask as a template to pad... Dynamic padding will be taken care of by the datacollator.
  model_inputs = tokenizer(formatted_texts, padding = False, max_length = 2048, truncation = True, return_tensors = None, return_attention_mask = True)

  #no need to pad here.
  model_inputs["labels"] = [input_ids.copy() for input_ids in model_inputs["input_ids"]]

  labels =[]

  #Instruction Masking...[probably not drastic immprovement in scores, still a good learning exercise]
  for i,(instruction, response) in enumerate(zip(examples['instruction'], examples['response'])):

    response_tokens = tokenizer(response, add_special_tokens = False, max_length = 2048, truncation = True)['input_ids']

    full_text = model_inputs['input_ids'][i]

    response_start = len(full_text) - len(response_tokens)

    temp = [-100] *len(full_text) #start with all tokens masked

    temp[response_start:] = full_text[response_start:] #unmask only the response tokens

    labels.append(temp)

  model_inputs['labels'] = labels

  return model_inputs




print("Converting data to HF Dataset format...")

train_dataset = Dataset.from_pandas(train_df[['instruction', 'response']])
val_dataset = Dataset.from_pandas(val_df[['instruction', 'response']])

print("Tokenizing Datasets...")

train_dataset = train_dataset.map(format_for_training, batched = True, remove_columns = ['instruction', 'response'], desc = "Formatting Train data")
val_dataset = val_dataset.map(format_for_training, batched = True, remove_columns = ['instruction', 'response'], desc = "Formatting Val data")

print("Datasets tokenized and formatted!")

print(f"Train dataset: {len(train_dataset)} examples")
print(f"Val dataset: {len(val_dataset)} examples")


print(f"\n Sample verification:")
for i in range(3):
    labels = train_dataset[i]['labels']
    learnable = sum(1 for l in labels if l != -100)
    print(f"Sample {i}: {learnable} learnable tokens")

Converting data to HF Dataset format...
Tokenizing Datasets...

Formatting Train data:   0%|          | 0/4390 [00:00<?, ? examples/s]

Formatting Val data:   0%|          | 0/1098 [00:00<?, ? examples/s]

Datasets tokenized and formatted!
Train dataset: 4390 examples
Val dataset: 1098 examples

 Sample verification:
Sample 0: 154 learnable tokens
Sample 1: 121 learnable tokens
Sample 2: 114 learnable tokens

In [ ]:
#Paste all the training args and training init and re-run

from transformers import TrainingArguments

OUTPUT_DIR = f"{DRIVE_PATH}/llama-3.2-3b-contract-analyzer"

os.environ["TENSORBOARD_LOGGING_DIR"] = f"{DRIVE_PATH}/logs2"

training_args = TrainingArguments(
    output_dir = OUTPUT_DIR,
    run_name = 'contract-clause-analysis',

    #Training Schedule
    num_train_epochs = 3,
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 16,
    per_device_eval_batch_size = 1,

    #Learning Rate params

    learning_rate = 2e-4,
    lr_scheduler_type = 'cosine',
    warmup_ratio = 0.03, #LR starts from 0 and reaches the peak of 2e-4 at the 3% of the total training steps and declines from there, big updates early on, finegrained updates towards the end.

    #Optimization
    optim = 'adamw_torch', #The paged version pushes data to RAM if VRAM is about to run out of memory, 8 bit version optimizes memory footprint.
    weight_decay = 0.01, #Adds a penalty to the model weights itself, not the LR, to make sure no weight is over-focused.
    max_grad_norm = 1.0, #Clips gradient and does not allow a norm of more than 1


    #Evaluation and Saving
    eval_strategy = 'steps', #model run on eval data every 50 train steps
    eval_steps = 100,
    save_strategy = 'steps', #model weights saved every 50 steps, usually in sync with the eval strategy so that we dont lose any info that was used for eval
    save_steps = 100,
    save_total_limit = 3, #saves the last 3 checkpoints.
    load_best_model_at_end = True,
    metric_for_best_model = 'eval_loss',

    #Logging
    logging_dir = f"{DRIVE_PATH}/logs",
    logging_steps = 10,
    report_to = 'none',

    #Memory Optimization
    gradient_checkpointing = True,
    fp16 =False,
    bf16 = False,

    remove_unused_columns = False,
    label_names = ['labels']

)

print("Training arguments configured")
print(f"\nKey Settings:")
print(f"Effective batch size: {training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps}")
print(f"Total epochs: {training_args.num_train_epochs}")
print(f"Learning rate: {training_args.learning_rate}")
print(f"Warmup steps: ~{int(len(train_dataset) / (training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps) * training_args.num_train_epochs * training_args.warmup_ratio)}")


#Supervised Fine-Tuning

from trl import SFTTrainer
from transformers import DataCollatorForLanguageModeling
from transformers import DataCollatorForSeq2Seq


#data_collator = DataCollatorForLanguageModeling(tokenizer, mlm = False)

data_collator = DataCollatorForSeq2Seq(
    tokenizer=tokenizer,
    model=model,
    padding=True,        # Pad dynamically
    pad_to_multiple_of=8,  # For efficiency
    label_pad_token_id=-100,  # Pad labels with -100
    return_tensors="pt"
)

#passing the datacollator handles the dynamic padding, max length sequence per batch

trainer = SFTTrainer(
    model = model,
    train_dataset = train_dataset,
    args = training_args,
    processing_class = tokenizer,
    eval_dataset = val_dataset,
    data_collator = data_collator
)

print("Trainer initialized!")
print("\nTraining will begin with:")
print(f"Total training steps: {trainer.state.max_steps if hasattr(trainer.state, 'max_steps') else 'calculating...'}")
print(f"Evaluation every: {training_args.eval_steps} steps")
print(f"Checkpoint every: {training_args.save_steps} steps")



import time

print("STARTING FINE-TUNING!")
print("Estimated time: 4-6 hours")
print("Checkpoints: Every 100 steps to Google Drive\n")

start_time = time.time()

# Train (has built-in progress bar)
trainer.train(resume_from_checkpoint=latest_checkpoint)

# Done
elapsed = (time.time() - start_time) / 3600
print(f"\nTRAINING COMPLETE in {elapsed:.2f} hours")

# Save
print("Saving model...")
final_model_path = f"{DRIVE_PATH}/final_model"
trainer.save_model(final_model_path)
tokenizer.save_pretrained(final_model_path)

print(f"Saved to: {final_model_path}")

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Training arguments configured

Key Settings:
Effective batch size: 16
Total epochs: 3
Learning rate: 0.0002
Warmup steps: ~24

Truncating train dataset:   0%|          | 0/4390 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/1098 [00:00<?, ? examples/s]

Trainer initialized!

Training will begin with:
Total training steps: 0
Evaluation every: 100 steps
Checkpoint every: 100 steps
STARTING FINE-TUNING!
Estimated time: 4-6 hours
Checkpoints: Every 100 steps to Google Drive

TRAINING COMPLETE in 0.93 hours
Saving model...
Saved to: /content/drive/MyDrive/CUAD_Project/final_model

In [ ]:
# ========================================
# CELL 21: Visualize Training Progress
# ========================================

import matplotlib.pyplot as plt

# Extract metrics from trainer
train_loss = [x['loss'] for x in trainer.state.log_history if 'loss' in x]
eval_loss = [x['eval_loss'] for x in trainer.state.log_history if 'eval_loss' in x]

steps_train = [x['step'] for x in trainer.state.log_history if 'loss' in x]
steps_eval = [x['step'] for x in trainer.state.log_history if 'eval_loss' in x]

# Plot
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(steps_train, train_loss, label='Train Loss', alpha=0.7)
plt.xlabel('Steps')
plt.ylabel('Loss')
plt.title('Training Loss')
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
plt.plot(steps_eval, eval_loss, label='Validation Loss', color='orange')
plt.xlabel('Steps')
plt.ylabel('Loss')
plt.title('Validation Loss')
plt.legend()
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(f'{DRIVE_PATH}/training_curves.png', dpi=150, bbox_inches='tight')
plt.show()

print("✅ Training curves saved to Google Drive")

# Print final metrics
print(f"\n📊 Final Metrics:")
print(f"   Final train loss: {train_loss[-1]:.4f}")
print(f"   Final val loss: {eval_loss[-1]:.4f}")
print(f"   Best val loss: {min(eval_loss):.4f}")

In [3]:
!hf auth login

    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    To log in, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Enter your token (input will not be visible):
Add token as git credential? [y/N]: N
Token is valid (permission: fineGrained).
The token `llama 3.3 70b label generation` has been saved to /root/.cache/huggingface/stored_tokens
Your token has been saved to /root/.cache/huggingface/token
Login successful.
The current active token is: `llama 3.3 70b label generation`

In [4]:
#Load the model for inference:

from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import torch

print("Loading fine-tuned model...")

#Load base model
base_model = AutoModelForCausalLM.from_pretrained(
    "meta-llama/Llama-3.2-3B-Instruct",
    device_map="auto",
    torch_dtype=torch.float16,
    trust_remote_code=True,
)

#load fine-tuned model
finetuned_model = PeftModel.from_pretrained(base_model, f"{DRIVE_PATH}/final_model", torch_dtype=torch.float16)

#Merge and unload solders the adapters' weights to the base weights, change is irreversible, reduces latency because the matrix multiplication required is reduced.
#Should be done only when all experimentation is done, as we cant separate the base model from adapters
#tricky to do when using 4 bit quantization, cos base weights are stored in float16 and soldering will lead to info loss.
#need to de-quantize before merging. NOTE: unload part makes sure all the adapter metadata are cleared from memory and we have only the new model infused with the adapters left.
#skipping for now...

#finetuned_model = finetuned_model.merge_and_unload()

tokenizer = AutoTokenizer.from_pretrained(f"{DRIVE_PATH}/final_model", trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = 'right'

print("Fine-tuned model loaded!")
print(f"Memory: {torch.cuda.memory_allocated() / 1e9:.2f} GB")

Loading fine-tuned model...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/878 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/20.9k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

Fine-tuned model loaded!
Memory: 6.52 GB

In [5]:
#Inference Function:

def analyze_clause(clause_text, contract_type="Service Agreement", jurisdiction="Delaware", renewal_term = "Not Applicable", notice_period = "none",key_provisions = [],
                   target_clause =""):


    instruction = f"""Analyze the following contract clause and provide:
1. Clause Type Classification
2. Risk assessment (HIGH/MEDIUM/LOW) with explanation
3. Plain English summary


**Contract Context:**
Type: {contract_type}
Jurisdiction: {jurisdiction}

**Clause Text:**
{clause_text}

Provide your analysis:"""

    instruction = f"""
  Analyse the following clause and provide:
1. Clause type classification
2. Risk assessment (HIGH/MEDIUM/LOW) with explanation
3. Plain English summary

**Contract Context:**
    Contract Type: {contract_type}
Jurisdiction : {jurisdiction}
Renewal Term: {renewal_term}
Notice Period to terminate renewal: {notice_period}
Key Provisions: {', '.join(key_provisions)}

    **Target Clause Type:** {target_clause}
    **Clause Text:**
      {clause_text}

Provide your analysis:
"""

  #tokenize the inference input
    inputs = tokenizer(instruction, return_tensors = 'pt', truncation = True, max_length = 2048).to(finetuned_model.device)

  #generate
    with torch.no_grad():

      outputs = finetuned_model.generate(**inputs, max_new_tokens = 350, temperature = 0.3, do_sample=True,top_p=0.9, pad_token_id=tokenizer.eos_token_id,
                                         eos_token_id=tokenizer.eos_token_id,)

      full_output = tokenizer.decode(outputs[0], skip_special_tokens = True)


      response = full_output[len(instruction):].strip()

      return response


print("Inference function ready!")

Inference function ready!

In [6]:
#testing the inference function

test_clauses = [
    {   "text":"the franchisee will not directly or indirectly, at any time during the term of this agreement or thereafter, do or cause to be done any act or thing disputing, attacking or in any way impairing the validity of and bkc's right, title or interest in the burger king marks and the burger king system.",
        "type": "Franchise Agreement",
        "jurisdiction": "Florida",
        "clause_type": 'Non-Disparagement',
        "key_provisions": ["Change of Control", "Cap on Liability", "Minimum Commitment"]
    },
    {
        "text": "during the term of this agreement, and for a period of two (2) years thereafter, aucta shall not research, develop, manufacture, file, sell, market, or distribute more than two products containing the active ingredient lamotrigine; nor will aucta directly or indirectly assist any other person or entity in carrying or any such activities.",
        "type": "Exclusive License And Product Devevlopment Agreement",
        "jurisdiction": "Delaware",
        "clause_type": ' Non-Compete',
        "key_provisions": ['Termination for Convenience','Change of Control','Cap on Liability','Minimum Commitment']
    },
    {
        "text": "march 13, 1996",
        "type": "Agreement Date",
        "jurisdiction": "British Columbia,Canada"
    },
    {
        "text" :"franchisee shall not challenge, directly or indirectly, franchisor's interest in, or the validity of, any franchisor property, or any application for registration or trademark registration thereof or any rights of franchisor therein.",
        "type" : "Master Franchise Agreement",
        "jurisdiction": "New York",
        "clause_type": "Covenant Not to Sue",
        "key_provisions": ["Change of Control", "Cap on Liability", "Minimum Commitment"]
    },
    {
       'text': "its products are warranted free from defects of material or workmanship for 3 years after shipment from the manufacturer. equipment purchased from its, which becomes defective within that time period will be repaired by its at its headquarters in san antonio, texas at no cost to comware beyond cost of shipping the equipment to its.",
        'type': "Distributor Agreement",
        'jurisdiction' : "Texas",
        'renewal_term' : '6 months',
        'key_provisions' : ['Termination for Convenience','Change of Control','Cap on Liability','Minimum Commitment'],
        'target_clause' : 'Warranty Duration'
       },
    {
        'text': 'for clarity, a competitive transaction shall not include an agreement for use, integration or interfacing, or co-marketing, of the ehave companion solution with other services, solutions, devices, goods or products, where such other services, solutions, devices, goods or products do not contain the same or similar functionality of the ehave companion solution, but provides for a complementary solution.',
        'jurisdiction' : 'Ontario, Canada',
        'type': 'License and Reseller Agreement',
        'target_clause' : 'Competitive Restriction Exception',
        'key_provisions' : ['Termination for Convenience','Change of Control','Cap on Liability','Minimum Commitment']
    }
]


print("Testing fine-tuned model on 3 samples...\n")

for i, sample in enumerate(test_clauses):

  print("="*80)
  print(f"\nSample {i+1}:")
  print(f"Contract Type: {sample['type']}")
  print(f"Jurisdiction: {sample['jurisdiction']}")
  print(f"Clause Text: {sample['text']}")
  print("\nAnalysis:")
  print(analyze_clause(sample['text'], sample['type'], sample['jurisdiction']))
  print("="*80)

Testing fine-tuned model on 3 samples...

================================================================================

Sample 1:
Contract Type: Franchise Agreement
Jurisdiction: Florida
Clause Text: the franchisee will not directly or indirectly, at any time during the term of this agreement or thereafter, do or cause to be done any act or thing disputing, attacking or in any way impairing the validity of and bkc's right, title or interest in the burger king marks and the burger king system.

Analysis:
**Risk Assessment:** MEDIUM
**Explanation:** The clause restricts the franchisee's ability to dispute or impair BKC's rights to the Burger King marks and system, which could limit the franchisee's ability to defend themselves in a dispute. However, the risk is mitigated by the fact that the clause only applies to actions taken during or after the term of the agreement. The jurisdiction of Florida may also impact the enforceability of this clause, but the overall risk remains moderate.

**Plain English Summary:** The franchisee is not allowed to challenge BKC's ownership of the Burger King brand, which could limit the franchisee's ability to defend themselves in a dispute. This restriction applies to the franchisee's actions during and after the contract term.HeaderCode**

The risk assessment is medium because the clause restricts the franchisee's ability to challenge BKC's ownership rights, but the risk is mitigated by the fact that it only applies to the franchisee's actions during and after the contract term. The jurisdiction of Florida may also impact the enforceability of this clause, but the overall risk remains moderate. The franchisee's ability to dispute or impair BKC's rights is a significant concern, as it could limit their ability to defend themselves in a dispute. However, the risk is not extremely high because the clause is specific to the validity of BKC's rights and does not impose a broad or unrestricted obligation on the franchisee. The franchisee's freedom to act and make decisions is not significantly impaired by this clause. The risk is also mitigated by the fact that the contract type is a franchise agreement, which typically has a more defined and predictable scope of obligations and responsibilities. The jurisdiction of Florida may also impact the risk
================================================================================
================================================================================

Sample 2:
Contract Type: Exclusive License And Product Devevlopment Agreement
Jurisdiction: Delaware
Clause Text: during the term of this agreement, and for a period of two (2) years thereafter, aucta shall not research, develop, manufacture, file, sell, market, or distribute more than two products containing the active ingredient lamotrigine; nor will aucta directly or indirectly assist any other person or entity in carrying or any such activities.

Analysis:
**Clause Type:** Exclusive License And Product Devevlopment Agreement

**Risk Assessment:** HIGH
**Explanation:** The clause restricts Aucta's ability to develop and distribute more than two products containing the active ingredient Lamotrigine for a period of two years after the agreement term, which could limit Aucta's business growth and revenue streams. This restriction, combined with the exclusive nature of the agreement, increases the risk of Aucta being locked into a limited business strategy. The Delaware jurisdiction may also impact the enforceability and interpretation of this clause, further increasing the risk.

**Plain English Summary:** Aucta is not allowed to develop or sell more than two products containing a certain ingredient for two years after the agreement ends, which could limit its business growth. This restriction could hurt Aucta's ability to make money and grow its business.anchise**

**Clause Text:** During the term of this agreement, and for a period of two years thereafter, Aucta shall not research, develop, manufacture, file, sell, market, or distribute more than two products containing the active ingredient Lamotrigine, and Aucta shall not directly or indirectly assist any other person or entity in carrying out these activities. This clause restricts Aucta's ability to develop and sell products containing Lamotrigine for a period of two years after the agreement term. Aucta is also prohibited from assisting other entities in carrying out these activities. This restriction could limit Aucta's business growth and revenue streams. The clause is in effect for a period of two years after the agreement term, which could further restrict Aucta's ability to adapt to changing market conditions. The Delaware jurisdiction may also impact the
================================================================================
================================================================================

Sample 3:
Contract Type: Agreement Date
Jurisdiction: British Columbia,Canada
Clause Text: march 13, 1996

Analysis:
**Clause Text:** This clause is a blank space and does not contain any meaningful information. It appears to be a placeholder or a placeholder for a future clause. The contract type and jurisdiction do not provide any context to this clause. The risk assessment is low because the clause does not impose any obligations or liabilities on the parties. The contract type and jurisdiction do not affect the risk assessment of this clause.

**Clause Text:** This clause is a blank space and does not contain any meaningful information. It appears to be a placeholder or a future clause. The risk is low because it does not impose any obligations or liabilities on the parties. The contract type and jurisdiction do not affect the risk of this clause.

**Clause Text:** This clause is a blank space and does not contain any meaningful information. It appears to be a future clause. The risk is low because it does not impose any obligations or liabilities on the parties. The contract type and jurisdiction do not affect the risk of this clause.

**Clause Text:** This clause is a blank space and does not contain any meaningful information. It appears to be a future clause. The risk is low because it does not impose any obligations or liabilities on the parties. The contract type and jurisdiction do not affect the risk of this clause.

**Clause Text:** This clause is a blank space and does not contain any meaningful information. It appears to be a future clause. The risk is low because it does not impose any obligations or liabilities on the parties. The contract type and jurisdiction do not affect the risk of this clause.

**Clause Text:** This clause is a blank space and does not contain any meaningful information. It appears to be a future clause. The risk is low because it does not impose any obligations or liabilities
================================================================================
================================================================================

Sample 4:
Contract Type: Master Franchise Agreement
Jurisdiction: New York
Clause Text: franchisee shall not challenge, directly or indirectly, franchisor's interest in, or the validity of, any franchisor property, or any application for registration or trademark registration thereof or any rights of franchisor therein.

Analysis:
**Clause Analysis:** The clause restricts the franchisee's ability to challenge the franchisor's interests in or the validity of any franchisor property, which could limit the franchisee's ability to protect their own interests. This could be a significant risk for the franchisee, as it may prevent them from taking action to protect their business in the event of a dispute with the franchisor. The New York jurisdiction may also impact the enforceability of this clause, but the overall effect is to give the franchisor significant control over the franchisee's actions.

**Risk Assessment:** HIGH
**Explanation:** The clause poses a high risk to the franchisee as it restricts their ability to challenge the franchisor's interests or the validity of their property, which could lead to a loss of control over their business. This could be particularly problematic if the franchisor's interests or property are not in the franchisee's best interests. The New York jurisdiction may also limit the franchisee's ability to challenge the clause, increasing the risk.

**Plain English Summary:** This clause stops the franchisee from questioning the franchisor's ownership or control over certain properties, which could put the franchisee's business at risk. It gives the franchisor a lot of power over the franchisee's actions and interests.anchise clause text is not provided, but the overall effect is to limit the franchisee's ability to protect themselves. The franchisee is essentially forced to accept the franchisor's interests and property without question. This could be a significant problem for the franchisee if the franchisor's interests are not in their best interests. The franchisee may be unable to take action to protect their business if they have a problem with the franchisor. The franchisee
================================================================================
================================================================================

Sample 5:
Contract Type: Distributor Agreement
Jurisdiction: Texas
Clause Text: its products are warranted free from defects of material or workmanship for 3 years after shipment from the manufacturer. equipment purchased from its, which becomes defective within that time period will be repaired by its at its headquarters in san antonio, texas at no cost to comware beyond cost of shipping the equipment to its.

Analysis:
**Risk Assessment:** LOW
**Explanation:** The warranty clause provides a reasonable protection for Comware's products, and the repair process is clearly outlined, which reduces the risk of disputes or unforeseen costs. The fact that Comware is responsible for the repair and shipping costs to its headquarters in San Antonio, Texas, also limits the potential financial exposure. The Texas jurisdiction does not introduce any unique risks in this context.

**Plain English Summary:** Comware promises to fix or replace defective products for 3 years after they leave the manufacturer's facility, and Comware will cover the costs of repair and shipping to its headquarters in Texas. This warranty provision provides a level of protection for Comware's products and reduces the risk of costly disputes.HeaderCode**

**Risk Assessment:** LOW
**Explanation:** The warranty clause provides a reasonable protection for Comware's products, and the repair process is clearly outlined, which reduces the risk of disputes or costs. The clause also limits the potential costs to Comware by requiring the repair to be done at its headquarters in San Antonio, Texas, and at no cost to Comware beyond the cost of shipping. This suggests a low-risk arrangement for Comware. The jurisdiction of Texas also does not introduce any unique risks in this context. The contract type, distributor agreement, and the specific warranty clause, do not indicate a high-risk situation for Comware. The renewal term and notice period are not applicable in this case, which also does not affect the risk assessment. The key provisions of the contract are not mentioned, but based on the provided clause, the risk is low. The contract is a distributor agreement, which typically involves a relatively low-risk arrangement for the distributor, as the supplier is responsible for the warranty and repair
================================================================================
================================================================================

Sample 6:
Contract Type: License and Reseller Agreement
Jurisdiction: Ontario, Canada
Clause Text: for clarity, a competitive transaction shall not include an agreement for use, integration or interfacing, or co-marketing, of the ehave companion solution with other services, solutions, devices, goods or products, where such other services, solutions, devices, goods or products do not contain the same or similar functionality of the ehave companion solution, but provides for a complementary solution.

Analysis:
**Clause Type:** Key Provisions

**Clause Text:** For clarity, a competitive transaction shall not include an agreement for use, integration, or interfacing, or co-marketing, of the ehave companion solution with other services, solutions, devices, goods, or products, where such other services, solutions, devices, goods, or products do not contain the same or similar functionality of the ehave companion solution, but provides for a complementary solution.

**Clause Analysis:** The clause defines a 'competitive transaction' and excludes agreements for use, integration, or co-marketing of the ehave companion solution with other services, if the other services do not have the same or similar functionality. This clause may be subject to interpretation, and its application could impact the parties' rights and obligations under the agreement. The jurisdiction of Ontario, Canada, may also influence the interpretation of this clause, as Canadian law may have specific requirements or limitations on such agreements.

**Clause Risk Assessment:** MEDIUM
**Clause Explanation:** The clause may create ambiguity or disputes if the parties have different interpretations of what constitutes a 'competitive transaction' or a 'complementary solution'. The risk is medium because the clause is intended to clarify the scope of a competitive transaction, but its language may still be subject to interpretation. The jurisdiction of Ontario, Canada, may also impact the risk level of this clause.

**Clause Plain English Summary:** This clause defines what a 'competitive transaction' is and what doesn't count as one, to avoid agreements that might compete with the ehave companion solution. It's a way to clarify what is and is not a competitive deal.curity

**Clause Type:** Key Provisions

**Clause Text:** For clarity, a competitive transaction shall not
================================================================================

In [7]:
!pip install -q gradio

In [8]:
# ========================================
# GRADIO: Complete UI with Your Samples
# ========================================

import gradio as gr

def analyze_clause_wrapper(clause_text, target_clause, contract_type, jurisdiction,
                          renewal_term, notice_period,
                          has_liability_cap, has_termination, has_change_control, has_minimum_commitment):
    """
    Wrapper to convert UI inputs to your function signature
    """

    if not clause_text.strip():
        return "⚠️ Please enter clause text"

    if target_clause == "Select clause type...":
        return "⚠️ Please select clause type"

    # Build key provisions list
    key_provisions = []
    if has_liability_cap:
        key_provisions.append("Cap on Liability")
    if has_termination:
        key_provisions.append("Termination for Convenience")
    if has_change_control:
        key_provisions.append("Change of Control")
    if has_minimum_commitment:
        key_provisions.append("Minimum Commitment")

    # Call your actual function
    response = analyze_clause(
        clause_text=clause_text,
        contract_type=contract_type,
        jurisdiction=jurisdiction,
        renewal_term=renewal_term,
        notice_period=notice_period,
        key_provisions=key_provisions,
        target_clause=target_clause
    )

    return response


with gr.Blocks(title="Contract Risk Analyzer", theme=gr.themes.Soft()) as demo:

    gr.Markdown("""
    # ⚖️ Contract Risk Analyzer
    ### Context-Aware Legal Clause Analysis

    Fine-tuned Llama 3.2 3B (QLoRA) provides:
    - 🎯 Risk assessment with jurisdiction-aware reasoning
    - 📝 Plain English explanations
    - 🔍 Contract context integration
    """)

    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown("## 📝 Input")

            clause_input = gr.Textbox(
                label="Contract Clause Text",
                placeholder="Paste your contract clause here...",
                lines=6
            )

            target_clause_input = gr.Dropdown(
                choices=[
                    "Select clause type...",
                    "Non-Compete",
                    "Non-Disparagement",
                    "Covenant Not to Sue",
                    "Exclusivity",
                    "License Grant",
                    "Cap on Liability",
                    "Termination for Convenience",
                    "Change of Control",
                    "Minimum Commitment",
                    "Volume Restriction",
                    "Anti-Assignment",
                    "Post-Termination Services",
                    "Audit Rights",
                    "Insurance",
                    "Renewal Term",
                    "Notice to Terminate Renewal",
                    "IP Ownership Assignment",
                    "No-Solicit of Employees",
                    "Warranty Duration",
                    "Competitive Restriction Exception",
                ],
                value="Select clause type...",
                label="Clause Type",
                allow_custom_value=True
            )

            gr.Markdown("### Contract Context")

            with gr.Row():
                contract_type_input = gr.Dropdown(
                    choices=[
                        "Service Agreement",
                        "Employment Agreement",
                        "License Agreement",
                        "Distribution Agreement",
                        "Distributor Agreement",
                        "Franchise Agreement",
                        "Master Franchise Agreement",
                        "License and Reseller Agreement",
                        "Exclusive License And Product Development Agreement",
                        "NDA",
                        "Other"
                    ],
                    value="Service Agreement",
                    label="Contract Type",
                    allow_custom_value=True
                )

                jurisdiction_input = gr.Dropdown(
                    choices=[
                        "Delaware",
                        "California",
                        "New York",
                        "Texas",
                        "Florida",
                        "Illinois",
                        "Washington",
                        "Ontario, Canada",
                        "British Columbia, Canada",
                        "Other"
                    ],
                    value="Delaware",
                    label="Jurisdiction",
                    allow_custom_value=True
                )

            with gr.Row():
                renewal_term_input = gr.Textbox(
                    label="Renewal Term",
                    placeholder="e.g., 3 years, 6 months, Perpetual",
                    value="Not Applicable"
                )

                notice_period_input = gr.Textbox(
                    label="Notice Period to Terminate",
                    placeholder="e.g., 30 days, 60 days, none",
                    value="none"
                )

            gr.Markdown("### Key Provisions Present")

            with gr.Row():
                has_liability_cap = gr.Checkbox(label="Cap on Liability", value=False)
                has_termination = gr.Checkbox(label="Termination for Convenience", value=False)

            with gr.Row():
                has_change_control = gr.Checkbox(label="Change of Control", value=False)
                has_minimum_commitment = gr.Checkbox(label="Minimum Commitment", value=False)

            analyze_btn = gr.Button("🔍 Analyze Clause", variant="primary", size="lg")

        with gr.Column(scale=1):
            gr.Markdown("## 📊 Analysis")

            output = gr.Textbox(
                label="Model Output",
                lines=16,
                interactive=False,
                show_copy_button=True
            )

    gr.Markdown("## 💡 Real CUAD Dataset Examples")

    gr.Examples(
        examples=[
            [
                # Example 1: Non-Disparagement
                "the franchisee will not directly or indirectly, at any time during the term of this agreement or thereafter, do or cause to be done any act or thing disputing, attacking or in any way impairing the validity of and bkc's right, title or interest in the burger king marks and the burger king system.",
                "Non-Disparagement",
                "Franchise Agreement",
                "Florida",
                "Not Applicable",
                "none",
                True,   # Cap on Liability
                False,  # Termination for Convenience
                True,   # Change of Control
                True    # Minimum Commitment
            ],
            [
                # Example 2: Non-Compete
                "during the term of this agreement, and for a period of two (2) years thereafter, aucta shall not research, develop, manufacture, file, sell, market, or distribute more than two products containing the active ingredient lamotrigine; nor will aucta directly or indirectly assist any other person or entity in carrying or any such activities.",
                "Non-Compete",
                "Exclusive License And Product Development Agreement",
                "Delaware",
                "Not Applicable",
                "none",
                True,   # Cap on Liability
                True,   # Termination for Convenience
                True,   # Change of Control
                True    # Minimum Commitment
            ],
            [
                # Example 3: Covenant Not to Sue
                "franchisee shall not challenge, directly or indirectly, franchisor's interest in, or the validity of, any franchisor property, or any application for registration or trademark registration thereof or any rights of franchisor therein.",
                "Covenant Not to Sue",
                "Master Franchise Agreement",
                "New York",
                "Not Applicable",
                "none",
                True,   # Cap on Liability
                False,  # Termination for Convenience
                True,   # Change of Control
                True    # Minimum Commitment
            ],
            [
                # Example 4: Warranty Duration
                "its products are warranted free from defects of material or workmanship for 3 years after shipment from the manufacturer. equipment purchased from its, which becomes defective within that time period will be repaired by its at its headquarters in san antonio, texas at no cost to comware beyond cost of shipping the equipment to its.",
                "Warranty Duration",
                "Distributor Agreement",
                "Texas",
                "6 months",
                "none",
                True,   # Cap on Liability
                True,   # Termination for Convenience
                True,   # Change of Control
                True    # Minimum Commitment
            ],
            [
                # Example 5: Competitive Restriction Exception
                "for clarity, a competitive transaction shall not include an agreement for use, integration or interfacing, or co-marketing, of the ehave companion solution with other services, solutions, devices, goods or products, where such other services, solutions, devices, goods or products do not contain the same or similar functionality of the ehave companion solution, but provides for a complementary solution.",
                "Competitive Restriction Exception",
                "License and Reseller Agreement",
                "Ontario, Canada",
                "Not Applicable",
                "none",
                True,   # Cap on Liability
                True,   # Termination for Convenience
                True,   # Change of Control
                True    # Minimum Commitment
            ],
        ],
        inputs=[
            clause_input,
            target_clause_input,
            contract_type_input,
            jurisdiction_input,
            renewal_term_input,
            notice_period_input,
            has_liability_cap,
            has_termination,
            has_change_control,
            has_minimum_commitment
        ],
        label="Click any example to load it"
    )

    # Connect button
    analyze_btn.click(
        fn=analyze_clause_wrapper,
        inputs=[
            clause_input,
            target_clause_input,
            contract_type_input,
            jurisdiction_input,
            renewal_term_input,
            notice_period_input,
            has_liability_cap,
            has_termination,
            has_change_control,
            has_minimum_commitment
        ],
        outputs=output
    )

    gr.Markdown("""
    ---
    ### 📚 Project Details

    **Model:**
    - Base: Llama 3.2 3B Instruct
    - Fine-tuning: QLoRA (LoRA rank 16, alpha 32, ~20M trainable params)
    - Training: 3 epochs, 825 steps on 3,900 samples
    - Dataset: CUAD (Contract Understanding Atticus Dataset)

    **Key Learnings:**
    - Model performs best with rich contract context matching training distribution
    - Token-level cross-entropy loss prioritizes explanation fluency over discrete classification
    - Risk assessment quality benefits from jurisdiction and multi-provision context
    - Train/inference distribution alignment is critical for generative task performance

    **Evaluation:**
    - Risk classification: ~55-60% (vs 63% majority baseline)
    - Explanation quality: High (context-aware, legally sound reasoning)
    - Summarization: High (captures key points in plain language)
    """)

print("✅ Gradio interface ready!")

/tmp/ipython-input-1033/1984641036.py:45: DeprecationWarning: The 'theme' parameter in the Blocks constructor will be removed in Gradio 6.0. You will need to pass 'theme' to Blocks.launch() instead.
  with gr.Blocks(title="Contract Risk Analyzer", theme=gr.themes.Soft()) as demo:

✅ Gradio interface ready!

In [9]:
demo.launch(share = True, debug = True)

Colab notebook detected. This cell will run indefinitely so that you can see errors and logs. To turn off, set debug=False in launch().
* Running on public URL: https://bd0a65a483ae875344.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://bd0a65a483ae875344.gradio.live

In [10]:
!gradio deploy

Need 'write' access token to create a Spaces repo.
Creating new Spaces Repo in '/content'. Collecting metadata, press Enter to
accept default value.
Enter Spaces app title [content]: Legal Contract Risk analyzer and summarizer
Formatted to Legal_Contract_Risk_analyzer_and_summarizer.
Enter Gradio app file : app.py
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.12/dist-packages/gradio/cli/commands/deploy_space.py: │
│ 301 in deploy                                                                │
│                                                                              │
│   298 │   │   print(                                                         │
│   299 │   │   │   f"Creating new Spaces Repo in '{repo_directory}'. Collecti │
│   300 │   │   )                                                              │
│ ❱ 301 │   │   configuration = add_configuration_to_readme(                   │
│   302 │   │   │   title,                                                     │
│   303 │   │   │   app_file,                                                  │
│   304 │   │   )                                                              │
│                                                                              │
│ /usr/local/lib/python3.12/dist-packages/gradio/cli/commands/deploy_space.py: │
│ 53 in add_configuration_to_readme                                            │
│                                                                              │
│    50 │   │   │   or app_file                                                │
│    51 │   │   )                                                              │
│    52 │   if not app_file or not os.path.exists(app_file):                   │
│ ❱  53 │   │   raise FileNotFoundError("Failed to find Gradio app file.")     │
│    54 │   configuration["app_file"] = app_file                               │
│    55 │                                                                      │
│    56 │   configuration["sdk"] = "gradio"                                    │
╰──────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: Failed to find Gradio app file.

In [16]:
#uploading model to hf hub

# ========================================
# Upload Fine-Tuned Model to HF Hub
# ========================================

from huggingface_hub import HfApi, create_repo, login

# Login to HF
login()

# Create model repo
repo_name = "contract-analyzer-and-summarizer-Qlora"
username = "bharathgrinds"

create_repo(
    repo_id=f"{username}/{repo_name}",
    exist_ok=True,
    repo_type="model"
)

# Upload model files
print("Uploading model...")

# Your fine-tuned model path
model_path = f"{DRIVE_PATH}/final_model"

# Upload
api = HfApi()
api.upload_folder(
    folder_path=model_path,
    repo_id=f"{username}/{repo_name}",
    repo_type="model"
)

print(f"Model uploaded to: https://huggingface.co/{username}/{repo_name}")

Uploading model...

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   0%|          | 45.8kB / 97.3MB

  ...inal_model/tokenizer.json: 100%|##########| 17.2MB / 17.2MB

  ...l_model/training_args.bin:   2%|1         |   107B / 5.78kB

Model uploaded to: https://huggingface.co/bharathgrinds/contract-analyzer-and-summarizer-Qlora

In [15]:
!hf auth login

    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    To log in, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Enter your token (input will not be visible):
Add token as git credential? [y/N]: N
Token is valid (permission: write).
The token `legal_contract_analyzer_model_upload` has been saved to /root/.cache/huggingface/stored_tokens
Your token has been saved to /root/.cache/huggingface/token
Login successful.
The current active token is: `legal_contract_analyzer_model_upload`